# ------------------------------------------------------------
#  Manual production deployment workflow
# ------------------------------------------------------------

name: Deploy
on:
  workflow_dispatch:
    branding:
      icon: 'upload-cloud'
#   inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'PLACEHOLDER'

      - name: Deploy to all servers
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
        run: ./.github/workflows/redeploy/redeploy.sh
